export enum MessageCode {
  TASK_ADDED_TASK_TAKEN = 'TASK_ADDED_TASK_TAKEN',
  TASK_ADDED = 'TASK_ADDED',
  TASK_TAKEN = 'TASK_TAKEN',
  TASK_RELEASED = 'TASK_RELEASED',
  DO_SEARCH = 'DO_SEARCH',
  FINISHED = 'FINISHED',
}
